services:
  db2:
    image: icr.io/db2_community/db2:latest
    platform: linux/amd64
    container_name: db2
    privileged: true
    ports:
      - "50000:50000"
    environment:
      LICENSE: "accept"
      DB2INST1_PASSWORD: "db2inst1"
      DBNAME: "db2inst1"
      TZ: "Asia/Seoul"
    volumes:
      - db2_data:/database
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  db2_data: