spring:
  application:
    name: testautomation

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:db2://localhost:50000/db2inst1
    username: db2inst1
    password: db2inst1
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jdbc:
    template:
      fetch-size: 100
      max-rows: 1000

server:
  port: 9898

testcode:
  project-path: ${TESTCODE_PROJECT_PATH:/Users/jungmo/Desktop/wd/local-repo/kb/project/project-web-test-platform-testcodes}
  root-package: ${TESTCODE_ROOT_PACKAGE:testauto.testcode}

logging:
  level:
    org.springframework.jdbc.core: debug